version: "3.9"

services:
  crawl_subs:
    build: .
    command: ["python", "crawl_subs.py"]
  crawl_biz:
    build: .
    image: biz_crawler:master
    command: ["python", "./crawl_biz.py"]
    volumes:
      - /c/biz_crawl_data/:/var/opt
